language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - tip

install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get gopkg.in/labstack/echo.v1
  - go get github.com/smartystreets/goconvey
  - go get github.com/flosch/pongo2

script:
  - go test -v .